apiVersion: v1
kind: Service
metadata:
  name: secureauth-demo
  labels:
    app: secureauth-demo
spec:
  type: LoadBalancer
  selector:
    app: secureauth-demo
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      nodePort: 30080

---
# MEDIUM: NodePort service with no restrictions
apiVersion: v1
kind: Service
metadata:
  name: secureauth-demo-nodeport
  labels:
    app: secureauth-demo
spec:
  type: NodePort
  selector:
    app: secureauth-demo
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 31000
      protocol: TCP

# MEDIUM: No NetworkPolicy defined — all pods can communicate freely
